import Head from "next/head";
import { Header } from "../components/Header";
import {
  IconBrandGithub as GitHub,
  IconBrandTwitter as Twitter,
  IconBrandLinkedin as LinkedIn,
} from "@tabler/icons";
import { Hero } from "../components/Hero";

const navs = ["Home", "About", "Contact"];
const links = [
  {
    link: "https://github.com/bisratgirma",
    element: <GitHub key={1} />,
  },
  {
    link: "https://twitter.com/bisrat_girma_",
    element: <Twitter key={2} />,
  },
  {
    link: "https://linkedin.com/in/bisrat-girma",
    element: <LinkedIn key={3} />,
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header navs={navs} links={links} />
        <Hero />
      </main>
    </>
  );
}
