import Head from "next/head";
import { Header } from "../components/Header";
import {
  IconBrandGithub as GitHub,
  IconBrandTwitter as Twitter,
  IconBrandLinkedin as LinkedIn,
} from "@tabler/icons";

const navs = ["Home", "About", "Contact"];
const links = [
  <GitHub key={1} />,
  <Twitter key={2} />,
  <LinkedIn key={3} />,
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header navs={navs} links={links} />
      </main>
    </>
  );
}
